<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
	<PackageReference Include="CoreHtmlToImage" Version="1.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SMT.Access\SMT.Access.csproj" />
    <ProjectReference Include="..\SMT.Domain\SMT.Domain.csproj" />
    <ProjectReference Include="..\SMT.Notification\SMT.Notification.csproj" />
    <ProjectReference Include="..\SMT.ViewModel\SMT.ViewModel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Seagull.BarTender.Print">
      <HintPath>C:\Program Files\Seagull\BarTender 2019\SDK\Assemblies\Seagull.BarTender.Print.dll</HintPath>
    </Reference>
    <Reference Include="Seagull.Services.PrintScheduler">
      <HintPath>C:\Program Files\Seagull\BarTender 2019\SDK\Assemblies\Seagull.Services.PrintScheduler.dll</HintPath>
    </Reference>
    <Reference Include="Seagull.Services.PrintScheduler.Contracts">
      <HintPath>C:\Program Files\Seagull\BarTender 2019\SDK\Assemblies\Seagull.Services.PrintScheduler.Contracts.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
